# Generated by Django 6.0.7 on 2026-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
