# Generated by Django 6.0.7 on 2026-07-26 13:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.', max_length=150, unique=True, validators=[users.models.SpaceAllowedUsernameValidator()], verbose_name='username'),
        ),
    ]
