[project]
name = "cdpdtdjango"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "beautifulsoup4>=4.15.0",
    "crispy-bootstrap5>=2026.3",
    "django>=6.0.7",
    "django-crispy-forms>=2.6",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "django-solo>=2.5.1",
    "django-tinymce>=5.0.0",
    "gunicorn>=26.0.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.0.6",
]
