# Generated by Django 6.0.7 on 2026-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_article_illustrations_articlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='articles/files/'),
        ),
        migrations.DeleteModel(
            name='ArticleFile',
        ),
    ]
