# Generated by Django 6.0.7 on 2026-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_article_file_delete_articlefile'),
        ('users', '0005_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='can_post',
            field=models.ManyToManyField(blank=True, related_name='can_post_sections', to='users.role', verbose_name='Qui peut ecrire'),
        ),
        migrations.AlterField(
            model_name='section',
            name='can_read',
            field=models.ManyToManyField(blank=True, related_name='can_read_sections', to='users.role', verbose_name='Qui peut acceder'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name="lien d'URL"),
        ),
    ]
