# Generated by Django 6.0.7 on 2026-07-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bas_de_page', models.TextField()),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('url', models.URLField(blank=True, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
