# Generated by Django 6.0.7 on 2026-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitebody_backgound_image_alter_sitebody_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebody',
            name='backgound_image',
        ),
        migrations.AddField(
            model_name='sitebody',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitebody',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
