name: Deploy Prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          command_timeout: 15m
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/apps/croqueurs-prod
          
            git fetch origin
            git reset --hard origin/master
          
            docker compose build
            docker compose up -d
            docker image prune -f
